{% set name = "UHDM" %}
{% set version = "1.84" %}
{% set sha256 = "bb2acbdd294dd05660c78ba34704440032935b8bc77cae352c853533b5a7c583" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chipsalliance/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('uhdm', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - orderedmultidict
  host:
    - capnproto

test:
  commands:
    - test -f $PREFIX/bin/uhdm-cmp
    - test -f $PREFIX/bin/uhdm-dump
    - test -f $PREFIX/bin/uhdm-hier
    - test -f $PREFIX/bin/uhdm-lint

outputs:
  - name: uhdm

  - name: python-uhdm
    script: build.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - capnproto
        - python
        - swig
        - orderedmultidict
        - setuptools
        - {{ pin_subpackage("uhdm", exact=True) }}
      run:
        - python
        - orderedmultidict
        - {{ pin_subpackage("uhdm", exact=True) }}
    test:
      imports:
        - uhdm

about:
  home: https://github.com/chipsalliance/UHDM
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Universal Hardware Data Model. A complete modeling of the IEEE SystemVerilog Object Model with VPI Interface, Elaborator, Serialization, Visitor and Listener. Used as a compiled interchange format in between SystemVerilog tools. Compiles on Linux gcc, Windows msys2-gcc & msvc, OsX
  description: |
    Universal Hardware Data Model. A complete modeling of the IEEE SystemVerilog Object Model with VPI Interface, Elaborator, Serialization, Visitor and Listener. Used as a compiled interchange format in between SystemVerilog tools. Compiles on Linux gcc, Windows msys2-gcc & msvc, OsX
  dev_url: https://github.com/chipsalliance/UHDM

extra:
  recipe-maintainers:
    - timkpaine
